spring:
  application:
    name: ohhcode
  datasource:
#    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:ohhcode}?createDatabaseIfNotExist=true
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${MYSQLUSER:root}

    password: ${MYSQLPASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

# JWTS

jwt:
  secret:
    key: ${JWT_SECRET}
  expiry:
    ms: 86400000

# CLOUDINARY
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}




